language: node_js
node_js:
  - "5"

before_script:
  - npm install -g bower
  - npm install -g grunt

script:
  - npm test

after_success:
  - npm run coveralls
  - npm run codacy

notifications:
  - email: false

sudo: false